## Working With Missing Data

In [1]:
import pandas as pd

In [2]:
ebola = pd.read_csv("C:/Users/bhave/01. Supervised Learning/pandas_for_everyone-master/data/country_timeseries.csv")

In [3]:
ebola.head()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN

In [4]:
ebola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 18 columns):
Date                   122 non-null object
Day                    122 non-null int64
Cases_Guinea           93 non-null float64
Cases_Liberia          83 non-null float64
Cases_SierraLeone      87 non-null float64
Cases_Nigeria          38 non-null float64
Cases_Senegal          25 non-null float64
Cases_UnitedStates     18 non-null float64
Cases_Spain            16 non-null float64
Cases_Mali             12 non-null float64
Deaths_Guinea          92 non-null float64
Deaths_Liberia         81 non-null float64
Deaths_SierraLeone     87 non-null float64
Deaths_Nigeria         38 non-null float64
Deaths_Senegal         22 non-null float64
Deaths_UnitedStates    18 non-null float64
Deaths_Spain           16 non-null float64
Deaths_Mali            12 non-null float64
dtypes: float64(16), int64(1), object(1)
memory usage: 17.2+ KB

In [24]:
ebola['Cases_Guinea'].isnull()

0      False
1      False
2      False
3       True
4      False
5      False
6      False
7      False
8      False
9      False
10      True
11     False
12      True
13     False
14      True
15     False
16      True
17     False
18      True
19     False
20     False
21      True
22     False
23      True
24     False
25      True
26      True
27     False
28     False
29      True
       ...
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100     True
101    False
102     True
103     True
104    False
105    False
106    False
107     True
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
Name: Cases_Guinea, Length: 122, dtype: bool

In [15]:
ebola['Cases_Guinea'].isnull().sum()

29

In [22]:
ebola.isnull()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,False,False,False,True,False,True,True,True,True,True,False,True,False,True,True,True,True,True
1,False,False,False,True,False,True,True,True,True,True,False,True,False,True,True,True,True,True
2,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
3,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
4,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
5,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
6,False,False,False,True,False,True,True,True,True,True,False,True,False,True,True,True,True,True
7,False,False,False,False,False,True,True,True,True,True,True,False,False,True,True,True,True,True
8,False,False,False,True,False,True,True,True,True,True,False,True,False,True,True,True,True,True
9,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
10,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
11,False,False,False,True,False,True,True,True,True,True,False,True,False,True,True,True,True,True
12,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
13,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
14,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
15,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
16,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
17,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
18,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
21,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
22,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
23,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
24,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
25,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
26,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
27,False,False,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
28,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
29,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
93,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
94,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
95,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
96,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
97,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
98,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
99,False,False,False,True,False,True,True,True,True,True,False,True,False,True,True,True,True,True
100,False,False,True,False,False,True,True,True,True,True,True,True,False,True,True,True,True,True
101,False,False,False,True,False,True,True,True,True,True,False,True,False,True,True,True,True,True
102,False,False,True,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True
103,False,False,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
104,False,False,False,True,True,True,True,True,True,True,False,False,True,True,True,True,True,True
105,False,False,False,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True
106,False,False,False,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True
107,False,False,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True
108,False,False,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
109,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
110,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
111,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
112,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
113,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
114,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
115,False,False,False,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True
116,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
117,False,False,False,False,False,True,True,True,True,True,False,False,False,True,True,True,True,True
118,False,False,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
119,False,False,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
120,False,False,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True
121,False,False,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True,True

In [23]:
ebola.isnull().sum()

Date                     0
Day                      0
Cases_Guinea            29
Cases_Liberia           39
Cases_SierraLeone       35
Cases_Nigeria           84
Cases_Senegal           97
Cases_UnitedStates     104
Cases_Spain            106
Cases_Mali             110
Deaths_Guinea           30
Deaths_Liberia          41
Deaths_SierraLeone      35
Deaths_Nigeria          84
Deaths_Senegal         100
Deaths_UnitedStates    104
Deaths_Spain           106
Deaths_Mali            110
dtype: int64

In [16]:
# Count gives the total number of non null values
print(ebola.count())

Date                   122
Day                    122
Cases_Guinea            93
Cases_Liberia           83
Cases_SierraLeone       87
Cases_Nigeria           38
Cases_Senegal           25
Cases_UnitedStates      18
Cases_Spain             16
Cases_Mali              12
Deaths_Guinea           92
Deaths_Liberia          81
Deaths_SierraLeone      87
Deaths_Nigeria          38
Deaths_Senegal          22
Deaths_UnitedStates     18
Deaths_Spain            16
Deaths_Mali             12
dtype: int64

In [19]:
total_rows= ebola.shape[0]
total_missing= total_rows- ebola.count()
print(total_missing)

Date                     0
Day                      0
Cases_Guinea            29
Cases_Liberia           39
Cases_SierraLeone       35
Cases_Nigeria           84
Cases_Senegal           97
Cases_UnitedStates     104
Cases_Spain            106
Cases_Mali             110
Deaths_Guinea           30
Deaths_Liberia          41
Deaths_SierraLeone      35
Deaths_Nigeria          84
Deaths_Senegal         100
Deaths_UnitedStates    104
Deaths_Spain           106
Deaths_Mali            110
dtype: int64

In [25]:
import numpy as np

In [27]:
print(np.count_nonzero(ebola['Deaths_Liberia'].isnull()))

41

In [31]:
print(ebola['Deaths_Guinea'].value_counts(dropna= False).head())

NaN      30
157.0     2
70.0      2
310.0     2
29.0      1
Name: Deaths_Guinea, dtype: int64

In [44]:
ebola['Cases_Guinea'].fillna(0).head()

0    2776.0
1    2775.0
2    2769.0
3       0.0
4    2730.0
Name: Cases_Guinea, dtype: float64

In [47]:
ebola['Cases_Liberia'].fillna(method= 'ffill').head()

0       NaN
1       NaN
2    8166.0
3    8157.0
4    8115.0
Name: Cases_Liberia, dtype: float64

In [48]:
ebola['Cases_Mali'].fillna(method= 'bfill').tail()

117   NaN
118   NaN
119   NaN
120   NaN
121   NaN
Name: Cases_Mali, dtype: float64

In [50]:
ebola['Deaths_Guinea'].head(10)

0    1786.0
1    1781.0
2    1767.0
3       NaN
4    1739.0
5    1708.0
6    1697.0
7       NaN
8    1607.0
9    1586.0
Name: Deaths_Guinea, dtype: float64

In [52]:
ebola.Deaths_Guinea.interpolate().head()

0    1786.0
1    1781.0
2    1767.0
3    1753.0
4    1739.0
Name: Deaths_Guinea, dtype: float64

In [53]:
ebola['Cases_multiple'] = ebola['Cases_Guinea'] + \
ebola['Cases_Liberia'] + \
ebola['Cases_SierraLeone']

In [54]:
ebola_subset = ebola.loc[:, ['Cases_Guinea', 'Cases_Liberia',
'Cases_SierraLeone', 'Cases_multiple']]

print(ebola_subset.head(n=10))

   Cases_Guinea  Cases_Liberia  Cases_SierraLeone  Cases_multiple
0        2776.0            NaN            10030.0             NaN
1        2775.0            NaN             9780.0             NaN
2        2769.0         8166.0             9722.0         20657.0
3           NaN         8157.0                NaN             NaN
4        2730.0         8115.0             9633.0         20478.0
5        2706.0         8018.0             9446.0         20170.0
6        2695.0            NaN             9409.0             NaN
7        2630.0         7977.0             9203.0         19810.0
8        2597.0            NaN             9004.0             NaN
9        2571.0         7862.0             8939.0         19372.0